server:
  port: 8081
spring:
  application:
    name: SpringBootOAuth
security:
  oauth2:
    client:
      clientId: 821013285778430
      clientSecret: 9c10ed9972f9a4fde6c9483f7ddfe792
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

